const loanPersonnel = [
    "acct_fund",
    "ao_fund",
    "ad_fund",
    "dc",
    "compt",
    "dc_audit",
    "acct_fund",
    "ao_fund",
    "ad_fund",
    "dc",
    "compt",
    "dc_audit",
    "acct_fund",
    "ad_fund",
    "compt",
    "acct_fund",
    "ao_fund",
    "ad_fund",
    "dc",
    "compt",
    "dc_audit",
    "acct_cash",
    "acct_fund",
];

export default loanPersonnel;
